#### Stress Variables Feature Selection

**Methodology**
- Select Heat Stress, Water Stress and Water Avaliabilty indices during key devolopmental periods

In [1]:
import pandas as pd
print(pd.__version__)

2.2.3

In [ ]:
#import ec data
df_ec = pd.read_csv('6_Training_EC_Data_2014_2023.csv')

In [ ]:
df_ec.head(5)

,Env,HI30_pGerEme,HI30_pEmeEnJ,HI30_pEnJFlo,HI30_pFloFla,HI30_pFlaFlw,HI30_pFlwStG,HI30_pStGEnG,HI30_pEnGMat,HI30_pMatHar,...,LL__1,LL__2,LL__3,LL__4,LL__5,LL__6,LL__7,LL__8,LL__9,LL__10
0,DEH1_2014,1,5,0,23,4,7,26,2,1,...,0.030565,0.030565,0.030565,0.030269,0.069334,0.069334,0.179364,0.179364,0.179364,0.167243
1,GAH1_2014,0,2,0,26,4,7,29,2,1,...,0.022565,0.022565,0.029567,0.029761,0.029761,0.088368,0.088368,0.148904,0.148904,0.148904
2,IAH1c_2014,2,6,1,15,3,3,16,2,1,...,0.175867,0.175867,0.181313,0.181053,0.162927,0.162927,0.162927,0.090938,0.090938,0.090938
3,IAH2_2014,1,6,0,13,3,2,14,0,0,...,0.127380,0.127380,0.127254,0.127035,0.127035,0.127035,0.127035,0.090938,0.090938,0.090938
4,IAH3_2014,0,4,0,18,1,1,15,1,0,...,0.182344,0.182344,0.182344,0.198777,0.198581,0.198581,0.198581,0.153790,0.153790,0.153790

In [ ]:
len(df_ec)

#for 241 year-locations only.
#ec covariates for 30+ year-locations are missing

241

In [ ]:
#extract HI30 for plant growth stages between flower initation and end grain filling
#HI30 is number of days in given period where max temp > 30

hi30_columns = ['Env','HI30_pFloFla', 'HI30_pFlaFlw', 'HI30_pFlwStG','HI30_pStGEnG']
df_hi30 = df_ec[hi30_columns]

In [ ]:
df_hi30.head(5)

          Env  HI30_pFloFla  HI30_pFlaFlw  HI30_pFlwStG  HI30_pStGEnG
0   DEH1_2014            23             4             7            26
1   GAH1_2014            26             4             7            29
2  IAH1c_2014            15             3             3            16
3   IAH2_2014            13             3             2            14
4   IAH3_2014            18             1             1            15

In [ ]:
#Extract Eo for plant growth stages between emergence and end juvenile aswell as between flower initation and End grain fill
#Eo is Potential evaporation and transpiration of soil-plant system (water demand)

eo_columns = ['Env','Eo_pEmeEnJ', 'Eo_pFloFla', 'Eo_pFlaFlw', 'Eo_pFlwStG','Eo_pStGEnG']

df_eo = df_ec[eo_columns]

In [ ]:
df_eo.head(5)

          Env  Eo_pEmeEnJ  Eo_pFloFla  Eo_pFlaFlw  Eo_pFlwStG  Eo_pStGEnG
0   DEH1_2014    4.954702    6.061473    5.350742    5.160511    5.056948
1   GAH1_2014    3.921894    5.489788    5.831873    6.256104    6.118042
2  IAH1c_2014    5.276381    4.765921    5.211196    4.822730    4.154742
3   IAH2_2014    5.085663    4.771535    5.098869    4.696505    3.990947
4   IAH3_2014    5.257378    4.872267    4.929165    4.069268    3.735635

In [ ]:
len(df_hi30), len(df_eo)

(241, 241)

In [ ]:
df_ec_1 = pd.concat([df_hi30, df_eo.drop(columns='Env')], axis=1)

In [ ]:
df_ec_1.head(5)

,Env,HI30_pFloFla,HI30_pFlaFlw,HI30_pFlwStG,HI30_pStGEnG,Eo_pEmeEnJ,Eo_pFloFla,Eo_pFlaFlw,Eo_pFlwStG,Eo_pStGEnG,Es_pEmeEnJ,Es_pFloFla,Es_pFlaFlw,Es_pFlwStG,Es_pStGEnG
0,DEH1_2014,23,4,7,26,4.954702,6.061473,5.350742,5.160511,5.056948,2.062101,1.824845,1.531395,1.465610,1.968319
1,GAH1_2014,26,4,7,29,3.921894,5.489788,5.831873,6.256104,6.118042,2.069815,1.615565,1.457842,1.883140,2.121796
2,IAH1c_2014,15,3,3,16,5.276381,4.765921,5.211196,4.822730,4.154742,2.598864,1.807797,1.282684,1.191473,1.307576
3,IAH2_2014,13,3,2,14,5.085663,4.771535,5.098869,4.696505,3.990947,2.775337,1.728405,1.140108,1.066299,1.198763
4,IAH3_2014,18,1,1,15,5.257378,4.872267,4.929165,4.069268,3.735635,1.869997,1.640372,1.010015,0.917729,0.987430

In [ ]:
#the amount of water in layer 1-10 is available is Swmm_pGrowthStage_LayerNumber
#each layer is 20cm thick. Layer 1 is 0-20 cm, Layer 2 is 20-40 cm, and so on

swmm_columns = ['Env','SWmm_pEmeEnJ_1','SWmm_pEmeEnJ_2' , 'SWmm_pEmeEnJ_3','SWmm_pFloFla_4',
 'SWmm_pFlaFlw_4','SWmm_pFlwStG_4','SWmm_pStGEnG_4','SWmm_pFloFla_5',
 'SWmm_pFlaFlw_5','SWmm_pFlwStG_5','SWmm_pStGEnG_5','SWmm_pFloFla_6',
 'SWmm_pFlaFlw_6','SWmm_pFlwStG_6','SWmm_pStGEnG_6']

#water availiabilty of layer 1,2,3 for growth stages between emergence and end juvenile (0 - 60 cm)
#water availiabilty of layer 4,5,6 for growth stages between flowering and end grain fill (60-120 cm)


df_swmm = df_ec[swmm_columns]

In [ ]:
df_swmm.head(5)

,Env,SWmm_pEmeEnJ_1,SWmm_pEmeEnJ_2,SWmm_pEmeEnJ_3,SWmm_pFloFla_4,SWmm_pFlaFlw_4,SWmm_pFlwStG_4,SWmm_pStGEnG_4,SWmm_pFloFla_5,SWmm_pFlaFlw_5,SWmm_pFlwStG_5,SWmm_pStGEnG_5,SWmm_pFloFla_6,SWmm_pFlaFlw_6,SWmm_pFlwStG_6,SWmm_pStGEnG_6
0,DEH1_2014,0.085402,0.102759,0.102790,0.076749,0.056245,0.052768,0.063259,0.132129,0.105302,0.100725,0.092283,0.141962,0.123324,0.119064,0.107509
1,GAH1_2014,0.094306,0.111875,0.118415,0.087973,0.061104,0.058346,0.047279,0.090028,0.063770,0.059995,0.050858,0.155762,0.127270,0.122776,0.111701
2,IAH1c_2014,0.307659,0.325830,0.326905,0.351437,0.304717,0.283025,0.242075,0.316364,0.282956,0.267014,0.232621,0.314819,0.288113,0.273294,0.240889
3,IAH2_2014,0.255058,0.267395,0.262965,0.280050,0.240864,0.220772,0.229509,0.277216,0.245206,0.227531,0.212742,0.267569,0.249291,0.233327,0.209317
4,IAH3_2014,0.337717,0.367219,0.368880,0.396776,0.330295,0.312086,0.277494,0.397523,0.340555,0.324447,0.285787,0.385162,0.349934,0.335482,0.299098

In [ ]:
df_ec_2 = pd.concat([df_ec_1, df_swmm.drop(columns='Env')], axis=1)

In [ ]:
df_ec_2.head(5)

,Env,HI30_pFloFla,HI30_pFlaFlw,HI30_pFlwStG,HI30_pStGEnG,Eo_pEmeEnJ,Eo_pFloFla,Eo_pFlaFlw,Eo_pFlwStG,Eo_pStGEnG,...,SWmm_pFlwStG_4,SWmm_pStGEnG_4,SWmm_pFloFla_5,SWmm_pFlaFlw_5,SWmm_pFlwStG_5,SWmm_pStGEnG_5,SWmm_pFloFla_6,SWmm_pFlaFlw_6,SWmm_pFlwStG_6,SWmm_pStGEnG_6
0,DEH1_2014,23,4,7,26,4.954702,6.061473,5.350742,5.160511,5.056948,...,0.052768,0.063259,0.132129,0.105302,0.100725,0.092283,0.141962,0.123324,0.119064,0.107509
1,GAH1_2014,26,4,7,29,3.921894,5.489788,5.831873,6.256104,6.118042,...,0.058346,0.047279,0.090028,0.063770,0.059995,0.050858,0.155762,0.127270,0.122776,0.111701
2,IAH1c_2014,15,3,3,16,5.276381,4.765921,5.211196,4.822730,4.154742,...,0.283025,0.242075,0.316364,0.282956,0.267014,0.232621,0.314819,0.288113,0.273294,0.240889
3,IAH2_2014,13,3,2,14,5.085663,4.771535,5.098869,4.696505,3.990947,...,0.220772,0.229509,0.277216,0.245206,0.227531,0.212742,0.267569,0.249291,0.233327,0.209317
4,IAH3_2014,18,1,1,15,5.257378,4.872267,4.929165,4.069268,3.735635,...,0.312086,0.277494,0.397523,0.340555,0.324447,0.285787,0.385162,0.349934,0.335482,0.299098

In [ ]:
df_ec_2.columns

Index(['Env', 'HI30_pFloFla', 'HI30_pFlaFlw', 'HI30_pFlwStG', 'HI30_pStGEnG',
       'Eo_pEmeEnJ', 'Eo_pFloFla', 'Eo_pFlaFlw', 'Eo_pFlwStG', 'Eo_pStGEnG',
       'SWmm_pEmeEnJ_1', 'SWmm_pEmeEnJ_2', 'SWmm_pEmeEnJ_3', 'SWmm_pFloFla_4',
       'SWmm_pFlaFlw_4', 'SWmm_pFlwStG_4', 'SWmm_pStGEnG_4', 'SWmm_pFloFla_5',
       'SWmm_pFlaFlw_5', 'SWmm_pFlwStG_5', 'SWmm_pStGEnG_5', 'SWmm_pFloFla_6',
       'SWmm_pFlaFlw_6', 'SWmm_pFlwStG_6', 'SWmm_pStGEnG_6'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import MinMaxScaler

def normalize_features(df: pd.DataFrame, exclude_cols: list = None):
    """
    Normalizes all numeric columns in a dataframe using MinMaxScaler, excluding any specified in exclude_cols. 
    Deletes the original columns after normalization.
    
    Returns:
        pd.DataFrame: DataFrame with normalized columns replacing original columns
    """
    df = df.copy()
    scaler = MinMaxScaler()
    
    if exclude_cols is None:
        exclude_cols = []

    for col in df.select_dtypes(include=['number']).columns: 
        if col not in exclude_cols:
            df[col + '_Normalized'] = scaler.fit_transform(df[[col]])
            df.drop(columns=col, inplace=True)

    return df

df_normalised = normalize_features(df_ec_2, exclude_cols=['Env'])

In [ ]:
df_normalised.head(5)

,Env,HI30_pFloFla_Normalized,HI30_pFlaFlw_Normalized,HI30_pFlwStG_Normalized,HI30_pStGEnG_Normalized,Eo_pEmeEnJ_Normalized,Eo_pFloFla_Normalized,Eo_pFlaFlw_Normalized,Eo_pFlwStG_Normalized,Eo_pStGEnG_Normalized,...,SWmm_pFlwStG_4_Normalized,SWmm_pStGEnG_4_Normalized,SWmm_pFloFla_5_Normalized,SWmm_pFlaFlw_5_Normalized,SWmm_pFlwStG_5_Normalized,SWmm_pStGEnG_5_Normalized,SWmm_pFloFla_6_Normalized,SWmm_pFlaFlw_6_Normalized,SWmm_pFlwStG_6_Normalized,SWmm_pStGEnG_6_Normalized
0,DEH1_2014,0.470588,0.8,0.777778,0.714286,0.293717,0.546739,0.539309,0.328808,0.329545,...,0.059874,0.066995,0.205829,0.179590,0.167379,0.144467,0.224353,0.211990,0.203376,0.183802
1,GAH1_2014,0.558824,0.8,0.777778,0.800000,0.116123,0.409224,0.616843,0.524169,0.482482,...,0.070370,0.035175,0.122418,0.095519,0.088408,0.062940,0.252037,0.220083,0.210822,0.192022
2,IAH1c_2014,0.235294,0.6,0.333333,0.428571,0.349030,0.235103,0.516822,0.268576,0.199508,...,0.493153,0.423061,0.570836,0.539205,0.489800,0.420665,0.571113,0.549943,0.512753,0.445323
3,IAH2_2014,0.176471,0.6,0.222222,0.371429,0.316236,0.236454,0.498721,0.246068,0.175900,...,0.376010,0.398039,0.493276,0.462791,0.413246,0.381541,0.476327,0.470327,0.432581,0.383419
4,IAH3_2014,0.323529,0.2,0.111111,0.400000,0.345763,0.260684,0.471373,0.134223,0.139102,...,0.547837,0.493589,0.731630,0.655799,0.601159,0.525299,0.712226,0.676728,0.637498,0.559453